//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectShopManagment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbShoppingMallEntities : DbContext
    {
        public DbShoppingMallEntities()
            : base("name=DbShoppingMallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Expenditure> Expenditures { get; set; }
        public virtual DbSet<Floor> Floors { get; set; }
        public virtual DbSet<ManagerInfo> ManagerInfoes { get; set; }
        public virtual DbSet<Rent_Details> Rent_Details { get; set; }
        public virtual DbSet<Rental_Rechord> Rental_Rechord { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Stall> Stalls { get; set; }
        public virtual DbSet<Stall_Manager> Stall_Manager { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
    
        public virtual ObjectResult<Sp_Manager_Result> Sp_Manager(Nullable<int> msid)
        {
            var msidParameter = msid.HasValue ?
                new ObjectParameter("msid", msid) :
                new ObjectParameter("msid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Manager_Result>("Sp_Manager", msidParameter);
        }
    
        public virtual ObjectResult<Sp_StallDetails_Result> Sp_StallDetails(Nullable<int> sid)
        {
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_StallDetails_Result>("Sp_StallDetails", sidParameter);
        }
    }
}
