//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectShopManagment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Stall_Manager
    {
        public int ID { get; set; }
        public string ManagerName { get; set; }
        public string Email { get; set; }
        public Nullable<int> M_Stall { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public HttpPostedFileBase Imgfile { get; set; }

        public virtual Stall Stall { get; set; }
    }
}
