//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectShopManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stall()
        {
            this.Stall_Manager = new HashSet<Stall_Manager>();
        }
    
        public int ID { get; set; }
        public Nullable<int> StallNo { get; set; }
        public string StallName { get; set; }
        public Nullable<int> StallVolume { get; set; }
        public Nullable<int> S_Floor { get; set; }
    
        public virtual Floor Floor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stall_Manager> Stall_Manager { get; set; }
    }
}
